"""Added path column to Template

Revision ID: 1e0d89d85cd6
Revises: 
Create Date: 2025-03-07 12:28:24.516773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0d89d85cd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Add the column with a default value
    op.add_column('template', sa.Column('path', sa.String(), nullable=False, server_default='default_path'))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.BLOB(), nullable=False))
        batch_op.drop_column('path')

    # ### end Alembic commands ###
