"""add unique constraints to template

Revision ID: 855b24a29433
Revises: afeff7582461
Create Date: 2025-04-04 14:41:40.003916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855b24a29433'
down_revision = 'afeff7582461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_template')
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_template_name', ['name'])
        batch_op.create_unique_constraint('uq_template_path', ['path'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('_alembic_tmp_template',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('path', sa.VARCHAR(), server_default=sa.text("'default_path'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_template_name'),
    sa.UniqueConstraint('path', name='uq_template_path')
    )
    # ### end Alembic commands ###
