"""Remove content column from template

Revision ID: afeff7582461
Revises: 1e0d89d85cd6
Create Date: 2025-03-07 12:33:30.342644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afeff7582461'
down_revision = '1e0d89d85cd6'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('template') as batch_op:
        batch_op.drop_column('content')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.BLOB(), nullable=False))

    op.create_table('_alembic_tmp_template',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
